### ISSUE TITLE
Smart Mastering Demo Setup Instructions Fail

### ISSUE THREAD

**Issue by netdance** [marklogic-community/automatic-data-mastering#42]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:

Following instructions on the Develop branch, example/smartmastering.md, I get the following message when I get to  the `gradle mlDeploy` step.

> com.marklogic.client.MarkLogicIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8010

What behavior are you expecting?

I was expecting it to create the necessary resources as part of the deploy, but it's clearly not creating application servers before trying to reference them.

#### Tech details

Which Operating System are you using?  Mac

Which version of MarkLogic are you using?  Marklogic 9.0-5

Which version of the Data Hub Framework are you using?  Develop branch of the smart-mastering-demo project

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for gradle:**  
  `gradle mldeploy -d > command.log`
[command.log](https://github.com/marklogic-community/smart-mastering-demo/files/2004368/command.log)

**Comment by sfc-gh-rpughsley** [comment]
I've just had exactly the same error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> com.marklogic.client.MarkLogicIOException: java.net.ConnectException: Failed to connect to forensic-paradise-smart-ml1/172.28.128.3:8010

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

tried on both Mac and vagrant

**Comment by dmcassel** [comment]
Taking a look.

**Comment by dmcassel** [comment]
@netdance confirmed that he ran mldeploy from the `examples/smart-mastering` directory, which is the correct place.

**Comment by dmcassel** [comment]
Unable to reproduce (Docker hosted by Windows, ML 9.0-5). 

@netdance @robpml please provide:

- `gradle -v`
- default username/password in `gradle.properties` is admin/admin. If yours is different, please create `gradle-local.properties` and add `mlUsername=myuser` and `mlPassword=mypassword`. 
- check `8000_AccessLog.txt` and `8000_ErrorLog.txt` for errors

**Comment by sfc-gh-rpughsley** [comment]
```
./gradlew -v

------------------------------------------------------------
Gradle 3.4
------------------------------------------------------------

Build time:   2017-02-20 14:49:26 UTC
Revision:     73f32d68824582945f5ac1810600e8d87794c3d4

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.13.4 x86_64
```

user/pass is also admin/admin

no entries in the logs at time of issue. 

The connection string does seem strange - 
`Failed to connect to forensic-paradise-smart-ml1/172.28.128.3:8010`
which seems to be machine name/ipaddress:port ?

**Comment by netdance** [comment]
macpro-3756:Code jdriscol$ gradle -v

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

Otherwise same as robpml - no errors.  For that matter, no access log entries either.  It never tried to create the servers.

**Comment by netdance** [comment]
Correction:  there are access log entries.

mdm-admin and mdm-user roles are being created.

Full set of access logs:

127.0.0.1 - - [16/May/2018:00:49:39 +0800] "GET /manage/v2/servers HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:40 +0800] "GET /manage/v2/servers HTTP/1.1" 200 4202 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:40 +0800] "GET /manage/v2/servers/Admin/properties?group-id=Default HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/Admin/properties?group-id=Default HTTP/1.1" 200 3358 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/App-Services/properties?group-id=Default HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/App-Services/properties?group-id=Default HTTP/1.1" 200 3454 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/Documents/properties?group-id=Default HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/Documents/properties?group-id=Default HTTP/1.1" 200 3348 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/HealthCheck/properties?group-id=Default HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/HealthCheck/properties?group-id=Default HTTP/1.1" 200 3328 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/Manage/properties?group-id=Default HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/servers/Manage/properties?group-id=Default HTTP/1.1" 200 3452 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/roles HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/roles HTTP/1.1" 200 30924 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "PUT /manage/v2/roles/mdm-admin/properties HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "PUT /manage/v2/roles/mdm-admin/properties HTTP/1.1" 204 0 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/roles HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/roles HTTP/1.1" 200 30924 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "PUT /manage/v2/roles/mdm-user/properties HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "PUT /manage/v2/roles/mdm-user/properties HTTP/1.1" 204 0 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "GET /manage/v2/roles HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:41 +0800] "GET /manage/v2/roles HTTP/1.1" 200 30924 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:41 +0800] "PUT /manage/v2/roles/mdm-admin/properties HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:42 +0800] "PUT /manage/v2/roles/mdm-admin/properties HTTP/1.1" 204 0 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:42 +0800] "GET /manage/v2/roles HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:42 +0800] "GET /manage/v2/roles HTTP/1.1" 200 30924 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - - [16/May/2018:00:49:42 +0800] "PUT /manage/v2/roles/mdm-user/properties HTTP/1.1" 401 104 - "Apache-HttpClient/4.3.5 (java 1.5)"
127.0.0.1 - admin [16/May/2018:00:49:42 +0800] "PUT /manage/v2/roles/mdm-user/properties HTTP/1.1" 204 0 - "Apache-HttpClient/4.3.5 (java 1.5)"

**Comment by netdance** [comment]
Attached is the full debug output from:

`gradle mlDeploy --debug`

[out.txt](https://github.com/marklogic-community/smart-mastering-demo/files/2007110/out.txt)

**Comment by mhavey** [comment]
I am having the same issue. I have ML 905 and gradle 4.0. I modified gradle.properties to use different ports, as I am using the standing DHF ports already. I am attaching my gradle.properties and the stdout and stderr dumps of mlDeploy.

**Comment by mhavey** [comment]
[mhavey_props_stdout_stderr.zip](https://github.com/marklogic-community/smart-mastering-demo/files/2009552/mhavey_props_stdout_stderr.zip)

**Comment by stuartseow** [comment]
I am getting the same error as well.

> Task :mlDeployApp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> com.marklogic.client.MarkLogicIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8010

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
4 actionable tasks: 4 executed
macpro-5908:smart-mastering sseow$ gradle -version

------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Mac OS X 10.13.4 x86_64

**Comment by dmcassel** [comment]
Can someone affected by this bug schedule a webex with @paxtonhare?

**Comment by paxtonhare** [comment]
we've updated the code and instructions. Please try again.

**Comment by netdance** [comment]
Well, I got further this time.    Services are absolutely being created.  However, I get the following error later in the process:

macpro-3756:smart-mastering jdriscol$ gradle bootrun

> Configure project : 
/Users/jdriscol/.gradle/caches/modules-2/files-2.1/com.marklogic.community/smart-mastering-core/0.0.14/ad62a227fcfec488807eb6502fb61e17e34460ba/smart-mastering-core-0.0.14.zip

> Task :bootRun FAILED
08:23:49.448 [main] ERROR c.m.s.b.c.l.s.CommandLineJobRunner - At least 2 arguments are required: job_path and job_id.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1


Instructions say to run `gradle bootrun`  from the project home - I can't really guess what the project home is, so I just ran it from the same smart-mastering directory.  Regardless, it's saying that I also need to give two parameters, not sure what they should be.  Presumably there's still a gap in the documentation.  Apologies if I'm missing something which should be obvious.

**Comment by dmcassel** [comment]
@netdance "project home" refers to the directory where you cloned smart-mastering-demo, rather than the examples/smart-mastering directory. Please re-run `gradle bootrun` from the smart-mastering-demo directory and let us know what happens. 

Also, you having this trouble tells me the fault is in the documentation. We'll fix that once we figure out the gap.

**Comment by netdance** [comment]
so, I did a `cd ../..`

then `gradle bootrun`

```
Starting. Please wait...

09:57:16.558 [restartedMain] WARN  o.s.b.a.t.AbstractTemplateResolverConfiguration - Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
QuickStart UI is Ready and Listening on port 8080.

Open your browser to http://localhost:8080.     (We recommend you use Chrome or FireFox.)
09:57:22.125 [http-nio-8080-exec-1] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][http-nio-8080-exec-1] Exception processing template "index": Error resolving template "index", template might not exist or might not be accessible by any of the configured Template Resolvers
```

Going to http://localhost:8080 returns

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed May 23 10:01:23 SGT 2018
There was an unexpected error (type=Internal Server Error, status=500).
Error resolving template "index", template might not exist or might not be accessible by any of the configured Template Resolvers
```

I thought that maybe I should also run `gradle runui`, so I did that in a separate window, same directory as the bootrun.  It prompted me to go to port 4020.   OK, did that, going to http://localhost:4020 got me further.  Now I've started the DH Quickstart UI, logged in, and the pre-install check fails.

```
Staging Port Already In Use
The Staging port 8010 is already in use by the App Server smart-mastering-STAGING.
SOLUTION: Change the mlStagingPort property in gradle.properties to a free port.

Final Port Already In Use
The Final port 8011 is already in use by the App Server smart-mastering-FINAL.
SOLUTION: Change the mlFinalPort property in gradle.properties to a free port.

Job Port Already In Use
The Job port 8013 is already in use by the App Server smart-mastering-JOBS.
SOLUTION: Change the mlJobPort property in gradle.properties to a free port.

Trace Port Already In Use
The Trace port 8012 is already in use by the App Server smart-mastering-TRACING.
SOLUTION: Change the mlTracePort property in gradle.properties to a free port.
```

I assume this is related to the issue with creating servers that started this thread.

**Comment by paxtonhare** [comment]
@netdance try starting over.

go to the examples/smart-mastering folder from a cmd prompt. then run:

`gradle mlUndeploy -Pconfirm=true`

That should remove all the apservers, dbs, forests, etc.

Then run the bootrun and runui again.

**Comment by popzip** [comment]
@netdance keep us posted

**Comment by popzip** [comment]
Anyone other than @sashamitrovich able to get the demo running?
@dmcassel any outstanding updates to code or docs to make it work for others?

**Comment by dmcassel** [comment]
@popzip,  @paxtonhare pushed a change a while ago -- there were some config files missing that are now present. No other updates outstanding.

**Comment by netdance** [comment]
Just following up.  

I can confirm that after doing a fresh pull, following the instructions results in a working demo.

Thanks for the assist getting this set up.
