### ISSUE TITLE
Not able to run the smart-mastering demo project

### ISSUE THREAD

**Issue by somaiyahr** [marklogic-community/automatic-data-mastering#48]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
Following instructions for installing smart-mastering-demo project.
could not get through the step gradle mldeploy, it fails in hubPreInstallCheck

Short description of the problem:

Installed Datahub framework through below link
https://marklogic.github.io/marklogic-data-hub/tutorial/install/

Following Steps to run the Smart Mastering Demo
 1. gradle build
2. gradle mlDeploy

could not get through the step gradle mldeploy, it fails in hubPreInstallCheck

What behavior are you expecting?

#### Tech details

Which Operating System are you using?
Windows 7 home premium

Which version of MarkLogic are you using?
MarkLogic 9.0-5

Which version of the Data Hub Framework are you using?
DataHub framework 3.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
[myoutput.txt](https://github.com/marklogic-community/smart-mastering-demo/files/2087578/myoutput.txt)

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@somaiyahr do you already have some serves and databases configured inside of MarkLogic?

Are there any exceptions logged anywhere? I don't see any errors.

**Comment by somaiyahr** [comment]
**@paxtonhare**  I don't have any databases and servers configured in MarkLogic and also no exceptions logged anywhere.

**Comment by somaiyahr** [comment]
**@paxtonhare** I could proceed further from **hubPreInstallCheck** in gradle mldeploy and now build fails in different task.
Note: Trying now with fresh MarkLogic installation on different machine.
[output.txt](https://github.com/marklogic-community/smart-mastering-demo/files/2094004/output.txt)

**Comment by popzip** [comment]
This sounds like a Data Hub Framework issue not related to Smart Mastering. Can you log your issue in that project? https://github.com/marklogic/marklogic-data-hub/issues

**Comment by paxtonhare** [comment]
@somaiyahr I also updated the README with some troubleshooting steps to clean out gradle and maven caches. https://github.com/marklogic-community/smart-mastering-demo/tree/develop/examples/smart-mastering#something-is-wrong

That might help. Worth a try.

**Comment by somaiyahr** [comment]
@paxtonhare Thanks: I was able to run it successfully after following clean out gradle and maven caches.
